<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace backend\modules\event\models\base;

use Yii;

/**
 * This is the base-model class for table "invitation".
 *
 * @property integer $id
 * @property string $org_name1
 * @property string $org_name2
 * @property integer $pax
 * @property integer $event_id
 * @property string $registration_code
 *
 * @property \backend\modules\event\models\Event $event
 * @property \backend\modules\event\models\Registration[] $registrations
 * @property string $aliasModel
 */
abstract class Invitation extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'invitation';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['org_name1', 'pax', 'event_id', 'registration_code'], 'required'],
            [['pax', 'event_id'], 'integer'],
            [['org_name1', 'org_name2', 'registration_code'], 'string', 'max' => 255],
            [['registration_code'], 'unique'],
            [['event_id'], 'exist', 'skipOnError' => true, 'targetClass' => \backend\modules\event\models\Event::className(), 'targetAttribute' => ['event_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'org_name1' => Yii::t('app', 'Org Name1'),
            'org_name2' => Yii::t('app', 'Org Name2'),
            'pax' => Yii::t('app', 'Pax'),
            'event_id' => Yii::t('app', 'Event ID'),
            'registration_code' => Yii::t('app', 'Registration Code'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getEvent()
    {
        return $this->hasOne(\backend\modules\event\models\Event::className(), ['id' => 'event_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getRegistrations()
    {
        return $this->hasMany(\backend\modules\event\models\Registration::className(), ['invitation_id' => 'id']);
    }




}
