<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace backend\models\base;

use Yii;

/**
 * This is the base-model class for table "banner".
 *
 * @property integer $id
 * @property string $photo_banner
 * @property string $footer_text
 * @property string $aliasModel
 */
abstract class Banner extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'banner';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['footer_text'], 'required'],
            [['photo_banner'], 'string', 'max' => 45],
            [['footer_text'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'photo_banner' => Yii::t('app', 'Photo Banner'),
            'footer_text' => Yii::t('app', 'Footer Text'),
        ];
    }




}
