<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace backend\models\base;

use Yii;

/**
 * This is the base-model class for table "banner".
 *
 * @property integer $id
 * @property string $photo_banner
 * @property string $footer_text
 * @property string $bg_title
 * @property string $bg_menu
 * @property string $bg_menu_focus
 * @property string $bg_menu_active
 * @property string $bg_footer
 * @property string $aliasModel
 */
abstract class Banner extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'banner';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['footer_text', 'bg_title', 'bg_menu', 'bg_menu_focus', 'bg_menu_active', 'bg_footer'], 'required'],
            [['photo_banner'], 'string', 'max' => 45],
            [['footer_text', 'bg_title', 'bg_menu', 'bg_menu_focus', 'bg_menu_active', 'bg_footer'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'photo_banner' => 'Photo Banner',
            'footer_text' => 'Footer Text',
            'bg_title' => 'Bg Title',
            'bg_menu' => 'Bg Menu',
            'bg_menu_focus' => 'Bg Menu Focus',
            'bg_menu_active' => 'Bg Menu Active',
            'bg_footer' => 'Bg Footer',
        ];
    }




}
