<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace backend\models\base;

use Yii;

/**
 * This is the base-model class for table "gallery_translate".
 *
 * @property integer $id
 * @property string $title
 * @property string $detail
 * @property string $language
 * @property integer $gallery_id
 *
 * @property \backend\models\Gallery $gallery
 * @property string $aliasModel
 */
abstract class GalleryTranslate extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'gallery_translate';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['detail'], 'string'],
            [['language', 'gallery_id'], 'required'],
            [['gallery_id'], 'integer'],
            [['title', 'language'], 'string', 'max' => 45],
            [['gallery_id'], 'exist', 'skipOnError' => true, 'targetClass' => Gallery::className(), 'targetAttribute' => ['gallery_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'title' => Yii::t('app', 'Title'),
            'detail' => Yii::t('app', 'Detail'),
            'language' => Yii::t('app', 'Language'),
            'gallery_id' => Yii::t('app', 'Gallery ID'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getGallery()
    {
        return $this->hasOne(\backend\models\Gallery::className(), ['id' => 'gallery_id']);
    }




}
