<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace backend\models\base;

use Yii;

/**
 * This is the base-model class for table "home".
 *
 * @property integer $id
 * @property string $name
 * @property string $like
 * @property string $photo
 * @property integer $type_home_id
 *
 * @property \backend\models\TypeHome $typeHome
 * @property \backend\models\HomeTranslate[] $homeTranslates
 * @property string $aliasModel
 */
abstract class Home extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'home';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name', 'photo', 'type_home_id'], 'required'],
            [['type_home_id'], 'integer'],
            [['name', 'like', 'photo'], 'string', 'max' => 255],
            [['type_home_id'], 'exist', 'skipOnError' => true, 'targetClass' => \backend\models\TypeHome::className(), 'targetAttribute' => ['type_home_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('models', 'ID'),
            'name' => Yii::t('models', 'Name'),
            'like' => Yii::t('models', 'Like'),
            'photo' => Yii::t('models', 'Photo'),
            'type_home_id' => Yii::t('models', 'Type Home ID'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTypeHome()
    {
        return $this->hasOne(\backend\models\TypeHome::className(), ['id' => 'type_home_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getHomeTranslates()
    {
        return $this->hasMany(\backend\models\HomeTranslate::className(), ['home_id' => 'id']);
    }




}
