<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace backend\models\base;

use Yii;

/**
 * This is the base-model class for table "menu_translate".
 *
 * @property integer $id
 * @property string $language
 * @property string $name
 * @property integer $menu_id
 *
 * @property \backend\models\Menu $menu
 * @property string $aliasModel
 */
abstract class MenuTranslate extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'menu_translate';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['language', 'name', 'menu_id'], 'required'],
            [['menu_id'], 'integer'],
            [['language'], 'string', 'max' => 45],
            [['name'], 'string', 'max' => 255],
            [['menu_id'], 'exist', 'skipOnError' => true, 'targetClass' => Menu::className(), 'targetAttribute' => ['menu_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'language' => Yii::t('app', 'Language'),
            'name' => Yii::t('app', 'Name'),
            'menu_id' => Yii::t('app', 'Menu ID'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getMenu()
    {
        return $this->hasOne(\backend\models\Menu::className(), ['id' => 'menu_id']);
    }




}
