<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build
namespace backend\models\base;

use Yii;
use yii\behaviors\BlameableBehavior;

/**
 * This is the base-model class for table "menu".
 *
 * @property integer $id
 * @property string $name
 * @property string $link
 * @property string $status
 * @property integer $top
 * @property integer $left
 * @property integer $right
 * @property integer $bottom
 * @property integer $sort
 * @property string $created_date
 * @property string $updated_date
 * @property integer $menu_id
 * @property integer $content_id
 * @property integer $created_by
 * @property integer $updated_by
 *
 * @property \backend\models\Content $content
 * @property \backend\models\Menu $menu
 * @property \backend\models\Menu[] $menus
 * @property \backend\models\User $createdBy
 * @property \backend\models\User $updatedBy
 * @property \backend\models\MenuTranslate[] $menuTranslates
 * @property string $aliasModel
 */
abstract class Menu extends \yii\db\ActiveRecord
{

    /**
     * ENUM field values
     */
    const STATUS_1 = '1';
    const STATUS_0 = '0';

    var $enum_labels = false;

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'menu';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => BlameableBehavior::className(),
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name'], 'required'],
            [['status'], 'string'],
            [['top', 'left', 'right', 'bottom', 'sort', 'menu_id', 'content_id'], 'integer'],
            [['created_date', 'updated_date'], 'safe'],
            [['name', 'link'], 'string', 'max' => 255],
            [['content_id'], 'exist', 'skipOnError' => true, 'targetClass' => Content::className(), 'targetAttribute' => ['content_id' => 'id']],
            [['menu_id'], 'exist', 'skipOnError' => true, 'targetClass' => Menu::className(), 'targetAttribute' => ['menu_id' => 'id']],
            [['created_by'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['created_by' => 'id']],
            [['updated_by'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['updated_by' => 'id']],
            ['status', 'in', 'range' => [
                    self::STATUS_1,
                    self::STATUS_0,
                ]
            ]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'name' => Yii::t('app', 'Name'),
            'link' => Yii::t('app', 'Link'),
            'status' => Yii::t('app', 'Status'),
            'top' => Yii::t('app', 'Top'),
            'left' => Yii::t('app', 'Left'),
            'right' => Yii::t('app', 'Right'),
            'bottom' => Yii::t('app', 'Bottom'),
            'sort' => Yii::t('app', 'Sort'),
            'created_date' => Yii::t('app', 'Created Date'),
            'updated_date' => Yii::t('app', 'Updated Date'),
            'menu_id' => Yii::t('app', 'Menu ID'),
            'content_id' => Yii::t('app', 'Content ID'),
            'created_by' => Yii::t('app', 'Created By'),
            'updated_by' => Yii::t('app', 'Updated By'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getContent()
    {
        return $this->hasOne(\backend\models\Content::className(), ['id' => 'content_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getMenu()
    {
        return $this->hasOne(\backend\models\Menu::className(), ['id' => 'menu_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getMenus()
    {
        return $this->hasMany(\backend\models\Menu::className(), ['menu_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCreatedBy()
    {
        return $this->hasOne(\backend\models\User::className(), ['id' => 'created_by']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUpdatedBy()
    {
        return $this->hasOne(\backend\models\User::className(), ['id' => 'updated_by']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getMenuTranslates()
    {
        return $this->hasMany(\backend\models\MenuTranslate::className(), ['menu_id' => 'id']);
    }

    /**
     * get column status enum value label
     * @param string $value
     * @return string
     */
    public static function getStatusValueLabel($value)
    {
        $labels = self::optsStatus();
        if (isset($labels[$value])) {
            return $labels[$value];
        }
        return $value;
    }

    /**
     * column status ENUM value labels
     * @return array
     */
    public static function optsStatus()
    {
        return [
            self::STATUS_1 => Yii::t('app', self::STATUS_1),
            self::STATUS_0 => Yii::t('app', self::STATUS_0),
        ];
    }
}
