<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace backend\models\base;

use Yii;

/**
 * This is the base-model class for table "setting".
 *
 * @property integer $id
 * @property integer $has_photo
 * @property integer $has_video
 * @property integer $has_slide
 * @property integer $has_social_media
 * @property integer $has_menu_left
 * @property integer $has_menu_right
 * @property integer $has_menu_bottom
 * @property integer $has_menu_top
 * @property string $aliasModel
 */
abstract class Setting extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'setting';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['has_photo', 'has_video', 'has_slide', 'has_social_media', 'has_menu_left', 'has_menu_right', 'has_menu_bottom', 'has_menu_top'], 'integer']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'has_photo' => Yii::t('app', 'Has Photo'),
            'has_video' => Yii::t('app', 'Has Video'),
            'has_slide' => Yii::t('app', 'Has Slide'),
            'has_social_media' => Yii::t('app', 'Has Social Media'),
            'has_menu_left' => Yii::t('app', 'Has Menu Left'),
            'has_menu_right' => Yii::t('app', 'Has Menu Right'),
            'has_menu_bottom' => Yii::t('app', 'Has Menu Bottom'),
            'has_menu_top' => Yii::t('app', 'Has Menu Top'),
        ];
    }




}
