<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace backend\models\base;

use Yii;

/**
 * This is the base-model class for table "slider_translate".
 *
 * @property integer $id
 * @property string $language
 * @property string $title
 * @property string $details
 * @property integer $slider_id
 *
 * @property \backend\models\Slider $slider
 * @property string $aliasModel
 */
abstract class SliderTranslate extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'slider_translate';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['language', 'slider_id'], 'required'],
            [['details'], 'string'],
            [['slider_id'], 'integer'],
            [['language'], 'string', 'max' => 45],
            [['title'], 'string', 'max' => 255],
            [['slider_id'], 'exist', 'skipOnError' => true, 'targetClass' => Slider::className(), 'targetAttribute' => ['slider_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'language' => Yii::t('app', 'Language'),
            'title' => Yii::t('app', 'Title'),
            'details' => Yii::t('app', 'Details'),
            'slider_id' => Yii::t('app', 'Slider ID'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSlider()
    {
        return $this->hasOne(\backend\models\Slider::className(), ['id' => 'slider_id']);
    }




}
