<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace backend\models\base;

use Yii;
use yii\behaviors\BlameableBehavior;

/**
 * This is the base-model class for table "social_media".
 *
 * @property string $id
 * @property string $photo
 * @property string $icon
 * @property string $title
 * @property string $link
 * @property string $status
 * @property string $created_date
 * @property string $updated_date
 * @property integer $sort
 * @property integer $updated_by
 * @property integer $created_by
 *
 * @property \backend\models\User $createdBy
 * @property \backend\models\User $updatedBy
 * @property string $aliasModel
 */
abstract class SocialMedia extends \yii\db\ActiveRecord
{



    /**
    * ENUM field values
    */
    const STATUS_0 = '0';
    const STATUS_1 = '1';
    var $enum_labels = false;
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'social_media';
    }


    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => BlameableBehavior::className(),
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['status'], 'string'],
            [['created_date', 'updated_date'], 'safe'],
            [['sort'], 'integer'],
            [['photo', 'icon', 'title', 'link'], 'string', 'max' => 255],
            [['created_by'], 'exist', 'skipOnError' => true, 'targetClass' => \backend\models\User::className(), 'targetAttribute' => ['created_by' => 'id']],
            [['updated_by'], 'exist', 'skipOnError' => true, 'targetClass' => \backend\models\User::className(), 'targetAttribute' => ['updated_by' => 'id']],
            ['status', 'in', 'range' => [
                    self::STATUS_0,
                    self::STATUS_1,
                ]
            ]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'photo' => Yii::t('app', 'Photo'),
            'icon' => Yii::t('app', 'Icon'),
            'title' => Yii::t('app', 'Title'),
            'link' => Yii::t('app', 'Link'),
            'status' => Yii::t('app', 'Status'),
            'created_date' => Yii::t('app', 'Created Date'),
            'updated_date' => Yii::t('app', 'Updated Date'),
            'sort' => Yii::t('app', 'Sort'),
            'updated_by' => Yii::t('app', 'Updated By'),
            'created_by' => Yii::t('app', 'Created By'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCreatedBy()
    {
        return $this->hasOne(\backend\models\User::className(), ['id' => 'created_by']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUpdatedBy()
    {
        return $this->hasOne(\backend\models\User::className(), ['id' => 'updated_by']);
    }




    /**
     * get column status enum value label
     * @param string $value
     * @return string
     */
    public static function getStatusValueLabel($value){
        $labels = self::optsStatus();
        if(isset($labels[$value])){
            return $labels[$value];
        }
        return $value;
    }

    /**
     * column status ENUM value labels
     * @return array
     */
    public static function optsStatus()
    {
        return [
            self::STATUS_0 => Yii::t('app', self::STATUS_0),
            self::STATUS_1 => Yii::t('app', self::STATUS_1),
        ];
    }

}
