<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace backend\models\base;

use Yii;

/**
 * This is the base-model class for table "type_home_translate".
 *
 * @property integer $id
 * @property string $name
 * @property string $language
 * @property integer $type_home_id
 *
 * @property \backend\models\TypeHome $typeHome
 * @property string $aliasModel
 */
abstract class TypeHomeTranslate extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'type_home_translate';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['type_home_id'], 'required'],
            [['type_home_id'], 'integer'],
            [['name'], 'string', 'max' => 255],
            [['language'], 'string', 'max' => 45],
            [['type_home_id'], 'exist', 'skipOnError' => true, 'targetClass' => \backend\models\TypeHome::className(), 'targetAttribute' => ['type_home_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('models', 'ID'),
            'name' => Yii::t('models', 'Name'),
            'language' => Yii::t('models', 'Language'),
            'type_home_id' => Yii::t('models', 'Type Home ID'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTypeHome()
    {
        return $this->hasOne(\backend\models\TypeHome::className(), ['id' => 'type_home_id']);
    }




}
