<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace backend\models\base;

use Yii;

/**
 * This is the base-model class for table "type_home".
 *
 * @property integer $id
 * @property string $name
 * @property integer $status
 *
 * @property \backend\models\Home[] $homes
 * @property \backend\models\TypeHomeTranslate[] $typeHomeTranslates
 * @property string $aliasModel
 */
abstract class TypeHome extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'type_home';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name'], 'required'],
            [['status'], 'integer'],
            [['name'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('models', 'ID'),
            'name' => Yii::t('models', 'Name'),
            'status' => Yii::t('models', 'Status'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getHomes()
    {
        return $this->hasMany(\backend\models\Home::className(), ['type_home_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTypeHomeTranslates()
    {
        return $this->hasMany(\backend\models\TypeHomeTranslate::className(), ['type_home_id' => 'id']);
    }




}
