<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace backend\models\base;

use Yii;

/**
 * This is the base-model class for table "video_translate".
 *
 * @property string $id
 * @property string $language
 * @property string $title
 * @property integer $video_id
 *
 * @property \backend\models\Video $video
 * @property string $aliasModel
 */
abstract class VideoTranslate extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'video_translate';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['language', 'title', 'video_id'], 'required'],
            [['video_id'], 'integer'],
            [['language'], 'string', 'max' => 45],
            [['title'], 'string', 'max' => 255],
            [['video_id'], 'exist', 'skipOnError' => true, 'targetClass' => Video::className(), 'targetAttribute' => ['video_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'language' => Yii::t('app', 'Language'),
            'title' => Yii::t('app', 'Title'),
            'video_id' => Yii::t('app', 'Video ID'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getVideo()
    {
        return $this->hasOne(\backend\models\Video::className(), ['id' => 'video_id']);
    }




}
